export const cultivosBase = [
  { id: "ajo", nombre: "Ajo", material: "bulbo" },
  { id: "lavanda", nombre: "Lavanda", material: "esqueje" },
  { id: "quinoa", nombre: "Quinoa", material: "semilla" },
  { id: "brocoli", nombre: "Brócoli", material: "plantula" },
  { id: "chile", nombre: "Chile", material: "plantula" },
  { id: "tomate", nombre: "Tomate", material: "plantula" },
  { id: "maiz", nombre: "Maíz", material: "semilla" },
  { id: "aguacate_hass", nombre: "Aguacate Hass", material: "planta" },
  { id: "limon_persa", nombre: "Limón persa", material: "planta" },
  { id: "granada", nombre: "Granada", material: "planta" },
  { id: "olivo", nombre: "Olivo", material: "planta" },
  { id: "higo", nombre: "Higo", material: "esqueje" },
  { id: "durazno", nombre: "Durazno", material: "planta" }
];

export const cultivosAnalisis = [
  { id:"ajo", nombre:"Ajo", emoji:"🧄", categoria:"hortaliza", tempMin:0, tempMax:25, tempOptima:15, lluviaMin:300, lluviaMax:600, heladas:"sensible", duracion:9, precioFresco:25, precioTransformado:800, producto:"Ajo negro gourmet", plan:"free", material:"bulbo", analogosGlobales:[{cultivo:"Azafrán",region:"La Mancha, España",justificacion:"Cultivo mediterráneo de alto valor para zonas secas templadas."},{cultivo:"Echalote",region:"Bretaña, Francia",justificacion:"Bulbo gourmet viable en climas frescos con baja humedad."}] },
  { id:"lavanda", nombre:"Lavanda", emoji:"💜", categoria:"aromatica", tempMin:-10, tempMax:30, tempOptima:18, lluviaMin:400, lluviaMax:700, heladas:"tolerante", duracion:12, precioFresco:80, precioTransformado:600, producto:"Aceite esencial", plan:"free", material:"esqueje", analogosGlobales:[{cultivo:"Romero rastrero",region:"Provenza, Francia",justificacion:"Aromática perenne para clima seco templado y suelos drenados."},{cultivo:"Salvia officinalis",region:"Mediterráneo oriental",justificacion:"Demanda humedad moderada y tolera suelos pobres."}] },
  { id:"quinoa", nombre:"Quinoa", emoji:"🌾", categoria:"grano", tempMin:5, tempMax:35, tempOptima:20, lluviaMin:250, lluviaMax:500, heladas:"moderado", duracion:5, precioFresco:35, precioTransformado:180, producto:"Harina · granos", plan:"free", material:"semilla", analogosGlobales:[{cultivo:"Kañiwa",region:"Altiplano Bolivia-Perú",justificacion:"Grano andino rústico para altitud y baja precipitación."},{cultivo:"Teff",region:"Tierras altas de Etiopía",justificacion:"Cereal fino tolerante a sequía y con nicho saludable."}] },
  { id:"maiz", nombre:"Maíz", emoji:"🌽", categoria:"grano", tempMin:10, tempMax:40, tempOptima:25, lluviaMin:500, lluviaMax:800, heladas:"sensible", duracion:5, precioFresco:5, precioTransformado:22, producto:"Harina · tortillas", plan:"free", material:"semilla", analogosGlobales:[{cultivo:"Sorgo dulce",region:"Sahel africano",justificacion:"Cereal alternativo para calor, menor agua y transformación."},{cultivo:"Mijo perla",region:"India semiárida",justificacion:"Tolera sequía y calor donde el maíz pierde rendimiento."}] },
  { id:"tomate", nombre:"Tomate", emoji:"🍅", categoria:"hortaliza", tempMin:12, tempMax:32, tempOptima:24, lluviaMin:450, lluviaMax:750, heladas:"muy_sensible", duracion:4, precioFresco:18, precioTransformado:95, producto:"Salsa · deshidratado", plan:"free", material:"plantula", analogosGlobales:[{cultivo:"Tomate San Marzano",region:"Campania, Italia",justificacion:"Variedad industrial para salsa premium en clima cálido moderado."},{cultivo:"Physalis",region:"Andes tropicales",justificacion:"Fruto de alto valor con manejo similar en zonas templadas."}] },
  { id:"chile", nombre:"Chile", emoji:"🌶", categoria:"hortaliza", tempMin:15, tempMax:35, tempOptima:26, lluviaMin:500, lluviaMax:900, heladas:"muy_sensible", duracion:5, precioFresco:28, precioTransformado:180, producto:"Seco · salsa · polvo", plan:"free", material:"plantula", analogosGlobales:[{cultivo:"Pimentón de Murcia",region:"Murcia, España",justificacion:"Capsicum para secado en clima cálido y relativamente seco."},{cultivo:"Berbere",region:"Etiopía",justificacion:"Mezcla de chiles especiados con mercado gourmet de transformación."}] },
  { id:"brocoli", nombre:"Brócoli", emoji:"🥦", categoria:"hortaliza", tempMin:7, tempMax:24, tempOptima:16, lluviaMin:400, lluviaMax:600, heladas:"moderado", duracion:3, precioFresco:18, precioTransformado:95, producto:"Congelado · deshidratado", plan:"pro", material:"plantula", analogosGlobales:[{cultivo:"Kale",region:"Norte de Europa",justificacion:"Brassica de clima fresco con valor en deshidratado."},{cultivo:"Col romanesco",region:"Italia central",justificacion:"Nicho gourmet para ventanas frescas semejantes."}] },
  { id:"moringa", nombre:"Moringa", emoji:"🌿", categoria:"arbol_funcional", tempMin:18, tempMax:40, tempOptima:28, lluviaMin:500, lluviaMax:1500, heladas:"muy_sensible", duracion:8, precioFresco:60, precioTransformado:900, producto:"Polvo · cápsulas · té", plan:"pro", material:"semilla", analogosGlobales:[{cultivo:"Baobab",region:"África subsahariana",justificacion:"Árbol funcional para clima cálido seco con valor nutracéutico."},{cultivo:"Neem",region:"India semiárida",justificacion:"Árbol rústico para bioinsumos y zonas cálidas."}] },
  { id:"romero", nombre:"Romero", emoji:"🌿", categoria:"aromatica", tempMin:5, tempMax:32, tempOptima:20, lluviaMin:250, lluviaMax:650, heladas:"tolerante", duracion:10, precioFresco:55, precioTransformado:420, producto:"Aceite · deshidratado", plan:"pro", material:"esqueje", analogosGlobales:[{cultivo:"Tomillo",region:"Grecia mediterránea",justificacion:"Aromática de bajo requerimiento hídrico y alto valor seco."},{cultivo:"Orégano griego",region:"Balcanes",justificacion:"Demanda suelos drenados y clima templado seco."}] },
  { id:"albahaca", nombre:"Albahaca", emoji:"🌱", categoria:"aromatica", tempMin:12, tempMax:32, tempOptima:24, lluviaMin:500, lluviaMax:900, heladas:"muy_sensible", duracion:3, precioFresco:70, precioTransformado:360, producto:"Pesto · deshidratado", plan:"pro", material:"semilla", analogosGlobales:[{cultivo:"Shiso",region:"Japón",justificacion:"Hoja aromática de nicho para clima cálido húmedo moderado."},{cultivo:"Perilla",region:"Corea",justificacion:"Aromática culinaria con mercado especializado."}] },
  { id:"garbanzo", nombre:"Garbanzo", emoji:"🫘", categoria:"leguminosa", tempMin:8, tempMax:32, tempOptima:22, lluviaMin:250, lluviaMax:500, heladas:"moderado", duracion:5, precioFresco:22, precioTransformado:85, producto:"Harina · hummus", plan:"pro", material:"semilla", analogosGlobales:[{cultivo:"Lenteja beluga",region:"Canadá templado seco",justificacion:"Leguminosa para baja lluvia y mercado premium."},{cultivo:"Arveja seca",region:"Mediterráneo seco",justificacion:"Alternativa proteica en rotación de secano."}] },
  { id:"amaranto", nombre:"Amaranto", emoji:"🌾", categoria:"grano", tempMin:12, tempMax:35, tempOptima:24, lluviaMin:350, lluviaMax:700, heladas:"sensible", duracion:4, precioFresco:30, precioTransformado:160, producto:"Alegrias · harina", plan:"pro", material:"semilla", analogosGlobales:[{cultivo:"Fonio",region:"África occidental",justificacion:"Grano ancestral de ciclo corto y tolerante a sequía."},{cultivo:"Trigo sarraceno",region:"Himalaya templado",justificacion:"Pseudocereal de nicho para climas templados."}] },
  { id:"aguacate_hass", nombre:"Aguacate Hass", emoji:"🥑", categoria:"arbol_frutal", tempMin:10, tempMax:30, tempOptima:22, lluviaMin:700, lluviaMax:1400, heladas:"muy_sensible", duracion:36, precioFresco:45, precioTransformado:180, producto:"Aceite · guacamole · pulpa congelada", plan:"free", material:"planta", analogosGlobales:[{cultivo:"Macadamia",region:"Queensland, Australia",justificacion:"Frutal/nuez perenne para clima subtropical sin heladas fuertes."},{cultivo:"Lúcuma",region:"Valles interandinos de Perú",justificacion:"Frutal de alto valor para zonas templadas subtropicales."}] },
  { id:"limon_persa", nombre:"Limón persa", emoji:"🍋", categoria:"arbol_frutal", tempMin:12, tempMax:35, tempOptima:26, lluviaMin:800, lluviaMax:1800, heladas:"muy_sensible", duracion:30, precioFresco:18, precioTransformado:110, producto:"Aceite esencial · jugo · cáscara deshidratada", plan:"free", material:"planta", analogosGlobales:[{cultivo:"Yuzu",region:"Japón templado húmedo",justificacion:"Cítrico premium para mercados gourmet si no hay heladas severas."},{cultivo:"Bergamota",region:"Calabria, Italia",justificacion:"Cítrico para aceite esencial con clima templado cálido."}] },
  { id:"granada", nombre:"Granada", emoji:"🔴", categoria:"arbol_frutal", tempMin:5, tempMax:38, tempOptima:25, lluviaMin:250, lluviaMax:700, heladas:"moderado", duracion:30, precioFresco:35, precioTransformado:220, producto:"Arilos · jugo antioxidante · molasses", plan:"pro", material:"planta", analogosGlobales:[{cultivo:"Pistache",region:"Irán semiárido",justificacion:"Perenne de zonas secas con alta amplitud térmica."},{cultivo:"Jujube",region:"Norte de China",justificacion:"Frutal rústico para sequía y calor estival."}] },
  { id:"olivo", nombre:"Olivo", emoji:"🫒", categoria:"arbol_frutal", tempMin:2, tempMax:38, tempOptima:22, lluviaMin:250, lluviaMax:650, heladas:"tolerante", duracion:48, precioFresco:20, precioTransformado:160, producto:"Aceite de oliva · aceituna curada", plan:"pro", material:"planta", analogosGlobales:[{cultivo:"Almendro",region:"California mediterránea",justificacion:"Frutal/nuez de clima mediterráneo seco."},{cultivo:"Algarrobo",region:"Mediterráneo oriental",justificacion:"Árbol rústico para sequía y suelos pobres."}] },
  { id:"higo", nombre:"Higo", emoji:"🟣", categoria:"arbol_frutal", tempMin:5, tempMax:38, tempOptima:26, lluviaMin:300, lluviaMax:800, heladas:"moderado", duracion:24, precioFresco:38, precioTransformado:190, producto:"Higo seco · mermelada · pasta", plan:"pro", material:"esqueje", analogosGlobales:[{cultivo:"Dátil",region:"Norte de África",justificacion:"Frutal de calor seco cuando el agua de riego es controlable."},{cultivo:"Caqui",region:"Cuenca mediterránea",justificacion:"Frutal de nicho con transformación en seco."}] },
  { id:"durazno", nombre:"Durazno", emoji:"🍑", categoria:"arbol_frutal", tempMin:3, tempMax:32, tempOptima:21, lluviaMin:500, lluviaMax:900, heladas:"sensible", duracion:30, precioFresco:28, precioTransformado:130, producto:"Conserva · deshidratado · mermelada", plan:"pro", material:"planta", analogosGlobales:[{cultivo:"Albaricoque",region:"Anatolia, Turquía",justificacion:"Frutal de hueso para clima templado con frío moderado."},{cultivo:"Cereza ácida",region:"Europa oriental",justificacion:"Frutal transformable si existe suficiente frío invernal."}] }
];
